name: "Validate"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  hassfest:
    name: "Hassfest Validation"
    runs-on: "ubuntu-latest"
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: 🔍 Run hassfest validation
        uses: "home-assistant/actions/hassfest@master"

  hacs:
    name: "HACS Validation"
    runs-on: "ubuntu-latest"
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: 🔍 Run HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"

  validate-ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      - run: uvx ruff check .
      - run: uvx ruff format --check .

  validate-mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.13"
      - run: pip install mypy types-requests homeassistant-stubs voluptuous
      - run: mypy custom_components/mylight150
